# From https://github.com/google-github-actions/deploy-cloudrun
name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    env:
      BRANCH: ${GITHUB_REF##*/}
      SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      CLOUD_RUN_SERVICE: ahchecker
      CLOUD_RUN_REGION: europe-west1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true

      - name: Authorize Docker push
        run: |
          gcloud auth configure-docker

      - name: Build image
        run: |-
          docker build -t eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:${GITHUB_SHA::6} .

      - name: Push image
        run: |-
          docker push eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:${GITHUB_SHA::6}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0.2.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service: ${{ env.CLOUD_RUN_SERVICE }}
          image: eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:${GITHUB_SHA::6}
          region: ${{ env.CLOUD_RUN_REGION }}
          env_vars: POSTCODE=${{ secrets.POSTCODE }},HOUSENUMBER=${{ secrets.HOUSENUMBER }},SLACK_WEB_HOOK=${{ secrets.SLACK_WEB_HOOK }},SLACK_CHANNEL=${{ secrets.SLACK_CHANNEL }}
